#!/bin/bash
#
# God
#
# chkconfig: - 85 15
# description: start, stop, restart, status for God
#

RETVAL=0

case "$1" in
    start)
      /usr/local/rbenv/shims/god -P /var/run/god.pid -l /var/log/god.log
      /usr/local/rbenv/shims/god load /etc/god/*.god
      RETVAL=$?
      ;;
    stop)
      kill `cat /var/run/god.pid`
      RETVAL=$?
      ;;
    restart)
      kill `cat /var/run/god.pid`
      /usr/local/rbenv/shims/god -P /var/run/god.pid -l /var/log/god.log
      /usr/local/rbenv/shims/god load /etc/god/*.god
      RETVAL=$?
      ;;
    status)
      /usr/local/rbenv/shims/god status
      RETVAL=$?
      ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
